// Code generated by mockery. DO NOT EDIT.

package restmock

import (
	rest "github.com/adehikmatfr/go-pkg/v2/client/rest"
	mock "github.com/stretchr/testify/mock"
)

// DefaultRest is an autogenerated mock type for the DefaultRest type
type DefaultRest struct {
	mock.Mock
}

type DefaultRest_Expecter struct {
	mock *mock.Mock
}

func (_m *DefaultRest) EXPECT() *DefaultRest_Expecter {
	return &DefaultRest_Expecter{mock: &_m.Mock}
}

// MakeRequest provides a mock function with given fields: r
func (_m *DefaultRest) MakeRequest(r rest.Request) *rest.Result {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for MakeRequest")
	}

	var r0 *rest.Result
	if rf, ok := ret.Get(0).(func(rest.Request) *rest.Result); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*rest.Result)
		}
	}

	return r0
}

// DefaultRest_MakeRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MakeRequest'
type DefaultRest_MakeRequest_Call struct {
	*mock.Call
}

// MakeRequest is a helper method to define mock.On call
//   - r rest.Request
func (_e *DefaultRest_Expecter) MakeRequest(r interface{}) *DefaultRest_MakeRequest_Call {
	return &DefaultRest_MakeRequest_Call{Call: _e.mock.On("MakeRequest", r)}
}

func (_c *DefaultRest_MakeRequest_Call) Run(run func(r rest.Request)) *DefaultRest_MakeRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(rest.Request))
	})
	return _c
}

func (_c *DefaultRest_MakeRequest_Call) Return(_a0 *rest.Result) *DefaultRest_MakeRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *DefaultRest_MakeRequest_Call) RunAndReturn(run func(rest.Request) *rest.Result) *DefaultRest_MakeRequest_Call {
	_c.Call.Return(run)
	return _c
}

// NewDefaultRest creates a new instance of DefaultRest. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDefaultRest(t interface {
	mock.TestingT
	Cleanup(func())
}) *DefaultRest {
	mock := &DefaultRest{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
